export const LOGGER_TAGS = {
  STARTING_CHROMA_CLIENT: "STARTING_CHROMA_CLIENT",
  UPSERT_ITEM_START: "UPSERT_ITEM_START",
  UPSERT_ITEM_END: "UPSERT_ITEM_END",
  QUERY_START: "QUERY_START",
  QUERY_END: "QUERY_END",
  STARTING_BACKEND: "STARTING_BACKEND",
};
