export const LOGGER_TAGS = {
  STARTING_CHROMA_CLIENT: "STARTING_CHROMA_CLIENT",
  UPSERT_ITEM_START: "UPSERT_ITEM_START",
  UPSERT_ITEM_END: "UPSERT_ITEM_END",
  QUERY_START: "QUERY_START",
  QUERY_END: "QUERY_END",
  STARTING_BACKEND: "STARTING_BACKEND",
  GOOGLE_AUTH_CODE_RECIEVED: "GOOGLE_AUTH_CODE_RECIEVED",
  GENERATING_GOOGLE_AUTH_CODE: "GENERATING_GOOGLE_AUTH_CODE",
};
